//
// Created by chudonghao on 2019/9/23.
//

#ifndef STARMAPRECOGNITION_SRC_CORE_DESCRIPTOR3_H_
#define STARMAPRECOGNITION_SRC_CORE_DESCRIPTOR3_H_

class Descriptor3 {

};

#endif //STARMAPRECOGNITION_SRC_CORE_DESCRIPTOR3_H_
